[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://pis-mun-4-0-t02w.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
